### PR TITLE
Fix known issues: Tutorial 'Write HTTP clients & servers' doesn't workk as expected

### PR DESCRIPTION
**Pull request by Classy-Bear**
The issue was opened [here](https://github.com/dart-lang/site-www/issues/2646). The server finally ends (closes) the response(s). The file is served as it says in the tutorial.

### CODE REVIEW

**Comment by Classy-Bear** [comment]
@googlebot I signed it!

**Comment by kwalrath** [comment]
I can't see the difference... Can you tell me what changed?

**Comment by Classy-Bear** [comment]
Sure! The response wasn't being closed, since it wasn't being reached because of the `if`/`else` statement.

We had this:

```dart
if (await targetFile.exists()) {
...
} else { 
      ...
      await req.response.close();
}
```
If the file exists the response will not be closed because the else statement will not be executed. So I take out the line where the response is being closed and put it outside the else statement:
```dart
if (await targetFile.exists()) {
...
} else { 
      ...
}
await req.response.close();
```
So now matter what happen the response will be closed.

If the response is not closed, the response will hang and no file will be served.

**Comment by kwalrath** [comment]
Thanks! I missed that it had moved outside the braces.

**Comment by stevenanthonyrevo** [comment]
@kwalrath, I am sorry but I think there is a misunderstanding. 

The original pull request was [here]( https://github.com/dart-lang/dart-tutorials-samples/pull/61), more specifically [here](https://github.com/dart-lang/dart-tutorials-samples/pull/61/commits/c4f707e6491617ad8f9d0ed19dab70cf5a537f98), if there were questions or concerns, I should have received a review?

No worries, looks like the problem is solved already. 

But you are missing a few changes, I suggested in my PR.

**Pull request merged**
