### PR TITLE
simplify reverseText function in click me example

### PR DESCRIPTION
**Pull request by kasperpeulen**

### CODE REVIEW

**Comment by sethladd** [comment]
will this work for any string? (even crazy multi-byte unicode?)

**Comment by kasperpeulen** [comment]
oh no idea, I only tested it for 'Click me !' and 'Hello World'

otherwise, maybe: `new String.fromCharCodes(text.codeUnits.reversed);`

**Comment by Sfshaza** [comment]
Hey, Kasper!

Thanks so much for this!

I actually have a CL ready to go (but not sent out yet) that removes this example from the repo because it is no longer used on dartlang. In fact, it removes several examples that we are either not using on dartlang, or that we are now maintaining in DartPad.

**Comment by Sfshaza** [comment]
This example has been removed. Thanks for your feedback!

**Pull request closed without merging**
